### ISSUE TITLE
Don't force unwrap optionals.

### ISSUE THREAD

**Issue by nickmshelley** [oo20/ios-directory-listing-swift-realm-objectmapper-alamofire#1]
We avoid force unwrapped optionals and implicitly unwrapped optionals in our Swift code to reduce the likelihood of crashes. Can you refactor the app to get rid of those instances?

Please do this change as a pull request as opposed to committing directly to master.

**Comment by oo20** [comment]
Hi Nick,

I made the changes you requested.  I also created a pull request.  I do not see the ability to add you as a reviewer through the filter in GitHub.   You can still see the pull request though.

Michael

**Comment by oo20** [comment]
Thank you.  Merged to master.
