### ISSUE TITLE
Scrolling through list is choppy

### ISSUE THREAD

**Issue by stephanheilner** [oo20/ios-directory-listing-swift-realm-objectmapper-alamofire#2]
It should be buttery-smooth when scrolling up and down through this list. Could you look and see if there's anything you can do to make it scroll smoother?

**Comment by oo20** [comment]
@stephanheilner  The scrolling is very smooth now.  I created a pull request for review.  Thank you.

**Comment by stephanheilner** [comment]
Excellent, I will look as soon as I have a few minutes. Thanks!
